name: Test Action

on:
    workflow_dispatch:

jobs:
    print-hello-world:
        runs-on: ubuntu-24.04
        steps:
            - run: print("Hello World from an inline python script in a GitHub Action Workflow!")
              shell: python